In [3]:
#size of array

In [4]:
import numpy as np

In [5]:
a1=np.array([1,7,13,105])
print(a1.nbytes)


32


In [6]:
#program to create element wise comparison

In [7]:
a1=np.array([10,25,30,45,50])
a2=np.array([11,22,25,44,55])

for i in range(5):
    if a1[i]>a2[i]:
        print(f"{a1[i]}- a1 is greater")
    elif a1[i]==a2[i]:
        print("both value is equal")
    elif a1[i]<a2[i]:    
        print(f"{a2[i]}-a2 is greater")


11-a2 is greater
25- a1 is greater
30- a1 is greater
45- a1 is greater
55-a2 is greater


In [8]:
#create array of 10 zeroes,10ones,10fives,10 tens,10 twentys & 10 fiftys

In [9]:
arr1=np.zeros(10)
print(arr1)
arr1=np.ones(10)
print(arr1)
arr1=np.ones(10)*5
print(arr1)
arr1=np.ones(10)*10
print(arr1)
arr1=np.ones(10)*20
print(arr1)
arr1=np.ones(10)*50
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [10]:
#create array of integers from 30 to 70

In [11]:
arr1=np.arange(30,71)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [12]:
#create array of integers from 50 to 95

In [13]:
arr1=np.arange(50,96)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [14]:
#create array of even integers from 20 to 80

In [15]:
arr1=np.arange(20,81,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [16]:
#create array of odd integers from 20 to 80

In [17]:
arr1=np.arange(21,80,2)
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [18]:
#create array of 15 random integers

In [19]:
arr1=np.random.randint(10,40,15)
print(arr1)

[18 13 11 35 32 13 11 18 17 15 22 20 25 29 24]


In [20]:
#create array of 15 random integers

In [21]:
arr1=np.random.randint(30,50,10)
print(arr1)

[47 43 36 48 31 42 31 46 31 48]


In [22]:
#create array of 20 random integers

In [23]:
arr1=np.random.randint(50,90,20)
print(arr1)

[69 77 57 81 83 87 53 63 89 85 86 69 80 71 88 50 69 68 72 63]


In [24]:
#perform +,-,*,/ on two array

In [25]:
a1=np.array([10,20,30,40,50])
a2=np.array([12,24,36,48,50])
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a2/a1)


[ 22  44  66  88 100]
[2 4 6 8 0]
[ 120  480 1080 1920 2500]
[1.2 1.2 1.2 1.2 1. ]


In [26]:
#create a 3x4 matrix with values 10 to 21

In [27]:
arr1=np.array([10,11,12,13,14,15,16,17,18,19,20,21])
arr1=arr1.reshape(3,4)
print(arr1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [28]:
#create 3x3 identity matrix

In [29]:
arr1=np.zeros(9)
#arr1=arr1.reshape(3,3)
#for i in range(3):
arr1[0]=1
arr1[4]=1
arr1[8]=1
arr1=arr1.reshape(3,3)
print(arr1)
    

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#to find no. of rows & coloumns in a given matrix

In [31]:
arr1=np.array([10,20,30,40,50,60])
arr1=arr1.reshape(3,2)
print(arr1.shape)

arr1=np.array([[10,20,30],[40,50,60]])
dimensions=arr1.shape
rows,coloumns=dimensions
print(f"rows:{rows}")
print(f"coloumns:{coloumns}")    



(3, 2)
rows:2
coloumns:3


In [32]:
#create 5x5 matrix with elements on main diagonal 

In [48]:
arr1=np.diag([1,2,3,4,5])
print(arr1)        
        

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [49]:
#create 3x3x3 array with arbitary values

In [50]:
arr1=np.random.random((3,3,3))
print(arr1)

[[[0.31839156 0.11556723 0.30160624]
  [0.93466937 0.36950451 0.68523262]
  [0.7723562  0.48005506 0.5686088 ]]

 [[0.97673534 0.87042251 0.48536409]
  [0.22818597 0.26164372 0.83734822]
  [0.24431348 0.77154079 0.02825349]]

 [[0.16008333 0.88066041 0.82164129]
  [0.07263449 0.87813161 0.81820958]
  [0.34687038 0.66302762 0.95157682]]]


In [51]:
#create 2x3x4 array with arbitary values

In [52]:
arr1=np.random.random((2,3,4))
print(arr1)

[[[0.25062314 0.54577754 0.23767377 0.26635947]
  [0.10963698 0.19172919 0.19128789 0.39061738]
  [0.63648803 0.08164887 0.71362087 0.92608052]]

 [[0.60371059 0.11401348 0.11587844 0.08711317]
  [0.52981496 0.54725144 0.7176825  0.04281345]
  [0.91142054 0.22049136 0.0500494  0.88992986]]]


In [53]:
#convert a list of numeric values into a one-dimensional NumPy array

In [57]:
l1=[11,22,33,44,55,66]
print("original list:",l1)
a1=np.array(l1)
print("1D-array:",a1)

original list: [11, 22, 33, 44, 55, 66]
1D-array: [11 22 33 44 55 66]


In [58]:
#create a 3x3 matrix with values ranging from 2to 10

In [60]:
arr1=np.arange(2,11)
arr1=arr1.reshape(3,3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [61]:
#create an array with values ranging from 12 to 38

In [63]:
arr1=np.arange(12,38)
print("array:",arr1)

array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [64]:
#reverse an array (the first element becomes the last)

In [65]:
arr2 = arr1[::-1]//reverse array
print(arr2)


[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [66]:
#convert an data type into to a floating type

In [74]:
num=2
num=np.float64(num)
print(f"Dtype = {num.dtype}")

Dtype = float64


In [75]:
#to convert a list array

In [77]:
l1=[1,2,3,4,5,6]
arr1=np.array(arr1)
print("array:",arr1)

array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [78]:
#program to get the element-wise remainder of an array of division

In [80]:
arr1=np.array([10,20,30,40,50])
print(arr1/10)

[1. 2. 3. 4. 5.]


In [79]:
#program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3

In [81]:
arr1=np.arange(20,51)
print(arr1/3)

[ 6.66666667  7.          7.33333333  7.66666667  8.          8.33333333
  8.66666667  9.          9.33333333  9.66666667 10.         10.33333333
 10.66666667 11.         11.33333333 11.66666667 12.         12.33333333
 12.66666667 13.         13.33333333 13.66666667 14.         14.33333333
 14.66666667 15.         15.33333333 15.66666667 16.         16.33333333
 16.66666667]
